---
- name: Include App Variables
  include_vars: vars/main.yml

- name: Retrieve PAN-OS Facts
  paloaltonetworks.panos.panos_facts:
    provider: "{{ provider }}"

- name: Set panos_release fact
  set_fact:
    panos_release: "panos-{{ ansible_net_version.split('.')[0:2] | join('.') }}"

- name: Check Role Compatibility
  block:
    - name: "Alert Role Compatibility"
      debug:
        msg: "Current Software Major version is NOT currently supported by this role"

    - name: End playbook
      meta: end_play

  when: panos_release not in supported_versions

- include_tasks: "{{ panos_release }}.yml"

